name = "satpura-cabs"
compatibility_date = "2026-10-09"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "satpura-cabs"
database_id = "0cf8dce3-49e6-4d01-a0a3-2ec0d6142b12"
